const sushiData = [
  {
    name: "Сет Хокку 32 шт",
    description:
      "Запечений з крабовим міксом, Каліфорнія з крабовим міксом в кунжуті, Макі з лососем, Рол Філадельфія дует. 🎁РОЛ У ПОДАРУНОК: Каліфорнія Чікен. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price: 669,
    category: "sets",
    weight: 1160,
    id: 1,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-set-hokku-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    // START ROLS END SUSHI
  {
    name: "Філадельфія з лососем",
    description: "Рис, лосось, крем сир, авокадо, огірок, норі",
    price: 329,
    category: "rols",
    weight: 270,
    id: 2,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-lososem-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія дует",
    description:
      "Рис, лосось, тунець, крем сир, огірок, соус горіховий унагі, норі, кунжут",
    price: 299,
    category: "rols",
    weight: 280,
    id: 3,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0001-filadelfiya-duet-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з тунцем",
    description: "Рис, тунець, крем сир, авокадо, огірок, норі",
    price: 299,
    category: "rols",
    weight: 270,
    id: 4,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0001-rol-filadelfiya-z-tuncem-we.png?&w=650&format=auto&mode=fit&q=80",
  },

  {
    name: "Філадельфія з вугрем",
    description:
      "Рис, вугор, авокадо, крем сир, огірок, соус унагі, кунжут, норі",
    price: 399,
    category: "rols",
    weight: 280,
    id: 5,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-vugrem-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з копченим лососем",
    description: "Рис, копчений лосось, крем сир, авокадо, огірок, норі",
    price: 319,
    category: "rols",
    weight: 260,
    id: 6,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-kopchenim-lososem-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з тунцем в кунжуті",
    description: "Рис, тунець, крем сир,авокадо, кунжут, огірок, норі",
    price: 239,
    category: "rols",
    weight: 260,
    id: 7,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-tuncem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з лососем в кунжуті",
    description: "Рис, лосось, крем сир, авокадо, кунжут, огірок, норі",
    price: 249,
    category: "rols",
    weight: 260,
    id: 8,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-lososem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з копченим лососем в кунжуті",
    description:
      "Рис, копчений лосось, крем сир, авокадо, кунжут, огірок, норі",
    price: 239,
    category: "rols",
    weight: 250,
    id: 9,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-kopchenim-lososem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з вугрем в кунжуті",
    description: "Рис, вугор, крем сир, авокадо, кунжут, огірок, норі",
    price: 299,
    category: "rols",
    weight: 250,
    id: 10,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-vugrem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Філадельфія з креветкою в кунжуті",
    description:
      "Рис, креветка темпура, крем сир, авокадо, огірок, кунжут, норі",
    price: 219,
    category: "",
    weight: 250,
    id: 11,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-krevetkoyu-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія з лососем в кунжуті",
    description: "Рис, лосось, авокадо, огірок, кунжут, норі",
    price: 219,
    category: "rols",
    weight: 230,
    id: 12,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-lososem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія з крабовим міксом в кунжуті",
    description: "Рис, крабовий мікс, авокадо, огірок, кунжут, норі",
    price: 139,
    category: "rols",
    weight: 230,
    id: 13,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-krabovim-miksom-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія з копченим лососем в кунжуті",
    description: "Рис, копчений лосось, авокадо, огірок, кунжут, норі",
    price: 229,
    category: "rols",
    weight: 220,
    id: 14,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-kopchenim-lososem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },

  {
    name: "Каліфорнія з крабовим міксом в ікрі",
    description: "Рис, крабовий мікс, авокадо, огірок, ікра тобіко, норі",
    price: 229,
    category: "rols",
    weight: 230,
    id: 15,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-krabovim-miksom-v-ikri-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія з лососем в ікрі",
    description: "Рис, лосось, авокадо, огірок, ікра тобіко, норі",
    price: 279,
    category: "rols",
    weight: 230,
    id: 16,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-lososem-v-ikri-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія Чікен",
    description:
      "Рис, копчена курка, омлет, огірок, кунжут, соус горіховий унагі, норі",
    price: 149,
    category: "rols",
    weight: 240,
    id: 17,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-chiken-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  {
    name: "Каліфорнія з креветкою в кунжуті",
    description: "Рис, креветка, омлет, огірок, кунжут, соус унагі, норі",
    price: 199,
    category: "rols",
    weight: 240,
    id: 18,
    imageUrl:
      "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-krevetkoyu-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Каліфорнія з вугрем в кунжуті",
    description: "Рис, вугор, омлет, огірок, кунжут, соус унагі, норі",
    price: 219 ,
    category: "rols",
    weight: 240  ,
    id: 18 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kaliforniya-z-vugrem-v-kunzhuti-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Зелений Дракон",
    description: "Рис, огірок, вугор, авокадо, крабовий мікс, соус унагі, норі, кунжут",
    price:369  ,
    category: "rols",
    weight: 280  ,
    id: 19 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0003-zelenij-drakon-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Червоний Дракон",
    description: "Рис, лосось, авокадо, огірок, майонез, крабовий мікс, ікра тобіко, норі",
    price:399  ,
    category: "rols",
    weight: 280  ,
    id: 21 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-chervonij-drakon-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Золотий Дракон",
    description: "Рис, вугор, авокадо, огірок, кунжут, крабовий мікс, соус унагі, норі",
    price: 429 ,
    category: "rols",
    weight: 270  ,
    id: 22 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-zolotij-drakon-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Роял Рол",
    description: "Рис, копчена курка, салат айсберг, огірок, перець болгарський, соус світ чилі, кунжут, норі",
    price:199 ,
    category: "rols",
    weight: 260  ,
    id: 23 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0005-royal-rol-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Футомакі з креветкою у темпурі",
    description: "Рис, креветка темпура, крем сир, огірок, болгарський перець, норі",
    price: 219 ,
    category: "rols",
    weight: 260  ,
    id: 24 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-futomaki-z-krevetkoyu-v-tempuri-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
  // END ROLS END SUSHI

  // START deliveryDnepr
    {
    name: "Преміум сет 24 шт.",
    description: "Філадельфія з креветкою в кунжуті, Філадельфія з лососем, Філадельфія з тунцем. 🎁РОЛ У ПОДАРУНОК: Каліфорнія з крабовим міксом в кунжуті. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price: 799 ,
    category: "deliveryDnepr",
    weight: 1020  ,
    id: 25 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-premium-set-24-sht-we.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Філадельфія сет 24 шт.",
    description: "Рол Філадельфія дует, Філадельфія з креветкою в кунжуті, Філадельфія з тунцем в кунжуті. 🎁РОЛ У ПОДАРУНОК: Каліфорнія з крабовим міксом в кунжуті. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price:649  ,
    category: "deliveryDnepr",
    weight: 1020  ,
    id: 26 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-set-24-sht.jpg?&w=650&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Сансет 32 шт.",
    description: "Каліфорнія з крабовим міксом в кунжуті, Каліфорнія Чікен, Рол Філадельфія дует, Торі Рол (гострий). 🎁РОЛ У ПОДАРУНОК: Ніжний з лососем. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price:699  ,
    category: "deliveryDnepr",
    weight: 1260  ,
    id: 27 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-set-sanset-32-sht.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Хокку 32 шт.",
    description: "Запечений з крабовим міксом, Каліфорнія з крабовим міксом в кунжуті, Макі з лососем, Рол Філадельфія дует. 🎁РОЛ У ПОДАРУНОК: Каліфорнія Чікен. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price:669  ,
    category: "deliveryDnepr",
    weight: 1160  ,
    id:28 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-set-hokku-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: " Сет Фудзі 32 шт.",
    description: "Запечений з крабовим міксом, Каліфорнія темпура, Ніжний з куркою, Темпура рол з куркою. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price: 599 ,
    category: "deliveryDnepr",
    weight: 1080  ,
    id: 29 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0003-set-fudzi-32-sht.jpg?&w=650&format=auto&mode=fit&q=80",
  },
      {
    name: "Сет Самурай 32 шт.",
    description: "Каліфорнія Чікен, Темпура рол з куркою, Ніжний з куркою, Макі з огірком. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price: 449 ,
    category: "deliveryDnepr",
    weight: 900  ,
    id: 30 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0003-set-samuraj-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
      {
    name: "Комбо Тріпл фіш",
    description: "Купуй Філадельфію дует та Каліфорнію з копченим лососем в кунжуті, отримуй Макі з тунцем в подарунок🎁 Соєвий соус - 80 мл (2 шт). Імбир - 30 г. Васабі - 10 г.",
    price:528  ,
    category: "deliveryDnepr",
    weight:630   ,
    id: 31 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kombo-tripl-fish.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
        {
    name: "Комбо Міні Паті",
    description: "Купуй Філадельфію з лососем та Запечений з креветкою, отримуй Макі з креветкою в подарунок🎁 Соєвий соус - 80 мл (2 шт). Імбир - 30 г. Васабі - 10 г.",
    price: 588 ,
    category: "deliveryDnepr",
    weight: 700  ,
    id: 32 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kombo-mini-pati.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Комбо Cакура",
    description: "Рол Філадельфія дует, Макі з лососем зі знижкою -50%. Соєвий соус - 40 мл (1 шт). Імбир - 10 г. Васабі - 5 г.",
    price: 379 ,
    category: "deliveryDnepr",
    weight: 410  ,
    id: 33 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kombo-cakura-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },  {
    name: "Комбо Чізі чіз",
    description: "Ніжний з куркою, Запечений з крабовим міксом зі знижкою -50%. Соєвий соус - 40 мл (1 шт). Імбир - 10 г. Васабі - 5 г.",
    price:284  ,
    category: "deliveryDnepr",
    weight: 550  ,
    id: 34 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-kombo-chizi-chiz-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Філадельфія з лососем",
    description: "Рис, лосось, крем сир, авокадо, огірок, норі",
    price: 279 ,
    category: "deliveryDnepr",
    weight:  270 ,
    id: 35 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-z-lososem-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Запечений з креветкою",
    description: "Рис, креветка темпура, салат айсберг, сирний соус, болгарський перець, кунжут, огірок, норі",
    price: 229 ,
    category: "deliveryDnepr",
    weight: 300  ,
    id: 36 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-zapechenij-z-krevetkoyu-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
  
  // START stock (АКЦИИ)
  {
    name: "Сет Хокку 32 шт.",
    description: "Запечений з крабовим міксом, Каліфорнія з крабовим міксом в кунжуті, Макі з лососем, Рол Філадельфія дует. 🎁РОЛ У ПОДАРУНОК: Каліфорнія Чікен. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price: 669 ,
    category: "stock",
    weight: 1160  ,
    id: 37 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-set-hokku-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Філадельфія сет 24 шт.",
    description: "Рол Філадельфія дует, Філадельфія з креветкою в кунжуті, Філадельфія з тунцем в кунжуті. 🎁РОЛ У ПОДАРУНОК: Каліфорнія з крабовим міксом в кунжуті. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price: 649 ,
    category: "stock",
    weight:  1020 ,
    id:38 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-filadelfiya-set-24-sht.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Преміум сет 24 шт.",
    description: "Філадельфія з креветкою в кунжуті, Філадельфія з лососем, Філадельфія з тунцем. 🎁РОЛ У ПОДАРУНОК: Каліфорнія з крабовим міксом в кунжуті. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price: 799 ,
    category: "stock",
    weight: 1020  ,
    id:39 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-premium-set-24-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Сансет 32 шт.",
    description: "Каліфорнія з крабовим міксом в кунжуті, Каліфорнія Чікен, Рол Філадельфія дует, Торі Рол (гострий). 🎁РОЛ У ПОДАРУНОК: Ніжний з лососем. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price:699  ,
    category: "stock",
    weight: 1260  ,
    id: 40 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-set-sanset-32-sht.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Фудзі 32 шт.",
    description: "Запечений з крабовим міксом, Каліфорнія темпура, Ніжний з куркою, Темпура рол з куркою. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price:599  ,
    category: "stock",
    weight:  1080 ,
    id: 41 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0003-set-fudzi-32-sht.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Самурай 32 шт.",
    description: "Каліфорнія Чікен, Темпура рол з куркою, Ніжний з куркою, Макі з огірком. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price:449 ,
    category: "stock",
    weight: 900  ,
    id: 42 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0003-set-samuraj-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Тропік 32 шт.",
    description: "Кранч з тунцем, Роял Рол, Каліфорнія з креветкою в кунжуті, Футомакі з тунцем (гострий)",
    price: 549 ,
    category: "stock",
    weight: 1000  ,
    id: 43 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0001-siet-tropik-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Багато лосося 32 шт.",
    description: "Рол Філадельфія дует, Каліфорнія з лососем в кунжуті, Каліфорнія з креветкою в кунжуті, Макі з лососем. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price:699  ,
    category: "stock",
    weight: 880  ,
    id:44 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0001-set-bagato-lososya-32-sht.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Преміум сет 32 шт.",
    description: "Каліфорнія з лососем в кунжуті, Рол Філадельфія дует 2 шт, Філадельфія з креветкою в кунжуті. Соєвий соус - 80 мл (2 шт). Імбир - 20 г. Васабі - 10 г.",
    price:899  ,
    category: "stock",
    weight: 1040  ,
    id: 45 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0002-premium-set-32-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Риба моя 56 шт.",
    description: "Рол Філадельфія дует, Каліфорнія з креветкою в кунжуті, Кранч з тунцем, Футомакі з тунцем (гострий), Каліфорнія Чікен, Макі з тунцем, Макі з огірком. Соєвий соус – 120 мл (3 шт). Імбир – 40 г. Васабі – 20 г.",
    price:899  ,
    category: "stock",
    weight: 1520  ,
    id: 46 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0001-siet-riba-moia-56-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет з любов'ю 70 шт.",
    description: "Філадельфія з лососем, Філадельфія з креветкою, Каліфорнія з вугрем в кунжуті, Кранч з креветкою, Кранч з тунцем, Фелікс рол з тунцем, Футомакі з креветкою у темпурі, Макі з тунцем, Макі з креветкою Соєвий соус – 200 мл (5 шт). Імбир – 60 г. Васабі – 30 г.",
    price:1499 ,
    category: "stock",
    weight: 2030  ,
    id: 47 ,
    imageUrl: "https://cdn.wesushi.com.ua/ws-ukr/products/0001-siet-z-liuboviu-70-sht-we.jpg?&w=991&h=700&format=auto&mode=fit&q=80",
  },
    {
    name: "Сет Біг Паті 64 шт.",
    description: "",
    price:1299  ,
    category: "stock",
    weight: 2000  ,
    id:48 ,
    imageUrl: "Каліфорнія з лососем в кунжуті, Макі з тунцем, Рол Філадельфія дует, Кранч з креветкою, Ніжний з куркою, Запечений з крабовим міксом, Каліфорнія темпура, Темпура рол з куркою. Соєвий соус – 160 мл (4 шт). Імбир – 50 г. Васабі – 25 г.",
  },

  // END stock (АКЦИИ)
    
  // END deliveryDnepr
  // {
  //   name: "",
  //   description: "",
  //   price: ,
  //   category: "",
  //   weight:  ,
  //   id ,
  //   imageUrl: "",
  // },
];

module.exports = sushiData;